name: db-actions
on: push

jobs:
  database-manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ensure datamodel directory exists
        run: |
          mkdir -p ./datamodel
      - name: Setup test database
        run: |
          podman run -d --name oracle \
            -p 1521:1521 \
            -e ORACLE_RANDOM_PASSWORD=y \
            -e APP_USER: ${{ secrets.APP_USER }}
            -e APP_USER_PASSWORD: ${{ secrets.APP_USER_PASSWORD }}
            -v ./datamodel:/container-entrypoint-initdb.d \
            gvenzl/oracle-free:slim
          while [[ $(podman logs oracle 2>&1 | grep -c "DATABASE IS READY TO USE") == 0 ]]; do
            sleep 1;
          done;
      - uses: gvenzl/setup-oracle-sqlcl@v1
      - name: Run SQLcl
        run: |
          echo "SELECT country_code, official_name, population \
          FROM countries WHERE name = 'Austria';" \
          | sql ${{ secrets.APP_USER }}/${{ secrets.APP_USER_PASSWORD }}@localhost/FREEPDB1

  database-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir ${{ github.workspace }}/database-files
      - run: mkdir -p /datamodel
      - uses: gvenzl/setup-oracle-free@v1
        with:
          app-user: ${{ secrets.APP_USER }}
          app-user-password: ${{ secrets.APP_USER_PASSWORD }}
          volume: ${{ github.workspace }}/database-files
          setup-scripts: /datamodel
      - uses: gvenzl/setup-oracle-sqlcl@v1
      - name: Run SQLcl
        run: |
          echo "SELECT country_code, official_name, population \
          FROM countries WHERE name = 'Austria';" \
          | sql ${{ secrets.APP_USER }}/${{ secrets.APP_USER_PASSWORD }}@localhost/FREEPDB1
